#!/usr/bin/env perl
use warnings;
use strict;
#
# A small tool to access all the features of your irtoy
#
#

use File::Spec;

# allow the libs to be in the bin dir
use FindBin;
use lib File::Spec->catdir($FindBin::RealBin,"lib");

use Data::Dumper;
$Data::Dumper::Indent = 1;
$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Quotekeys = 0;

use Getopt::Long 2.33 qw(:config gnu_getopt no_auto_abbrev);

use IRToy;

my $option = {
};
my @option_list = (
    "port=s",
    "debug",
);

sub do_options {
    my $option = shift || die "no option!";
    my @option_list = grep {$_} @_;
    GetOptions($option,@option_list,'man','help|?') or pod2usage(2);
    if ($option->{help} && @option_list) {
        print("List of options:\n");
        print("\t");
        foreach(sort @option_list) {
            $_="--".$_;
        }
        print join(", ",@option_list);
        print("\n");
    }
    pod2usage(-exitstatus => 0, -verbose => 2) if $option->{man};

    if ($option->{quiet}) {
        delete $option->{verbose};
    }
}

sub main() {
    do_options($option,@option_list);
    return if (defined($option->{help}));

    die("Please specify port") if (!defined($option->{port}));

    my $toy = IRToy->new()->open($option->{port}) || die("couldnt open");
    $toy->debug($option->{debug});

    $toy->reset();
    $toy->mode_selftest();

}
main();

