#!/usr/bin/env perl
use warnings;
use strict;
#
# A small tool to access all the features of your irtoy
#
#

use File::Spec;

# allow the libs to be in the bin dir
use FindBin;
use lib File::Spec->catdir($FindBin::RealBin,"lib");

use Data::Dumper;
$Data::Dumper::Indent = 1;
$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Quotekeys = 0;

use Getopt::Long 2.33 qw(:config gnu_getopt no_auto_abbrev);

use IRToy ':consts';

my $option = {
};
my @option_list = (
    "port=s",
    "debug",
);

sub do_options {
    my $option = shift || die "no option!";
    my @option_list = grep {$_} @_;
    GetOptions($option,@option_list,'man','help|?') or pod2usage(2);
    if ($option->{help} && @option_list) {
        print("List of options:\n");
        print("\t");
        foreach(sort @option_list) {
            $_="--".$_;
        }
        print join(", ",@option_list);
        print("\n");
    }
    pod2usage(-exitstatus => 0, -verbose => 2) if $option->{man};

    if ($option->{quiet}) {
        delete $option->{verbose};
    }
}

sub main() {
    do_options($option,@option_list);
    return if (defined($option->{help}));

    die("Please specify port") if (!defined($option->{port}));

    my $toy = IRToy->new()->open($option->{port}) || die("couldnt open");
    $toy->debug($option->{debug});

    # Confirm that we have working comms with the device
    die("Can not communicate") if (!defined($toy->checkmode(IRToy::MODE_RC)));

    my $cmd = $ARGV[0] || '';
    if ($cmd eq 'check') {
        # done already above, so.. do nothing here
    #} elsif ($cmd eq 'rc_read') {
    #    while(1) {
    #        $toy->rc_read();
    #    }
    } elsif ($cmd eq 'selftest') {
        # TODO - pass or fail result
        print($toy->selftest(),"\n");
    } elsif ($cmd eq 'sample_settings') {
        # TODO - this simply prints binary data!
        print($toy->sample_settings(),"\n");
    } elsif ($cmd eq 'sumpmeta') {
        # TODO - this simply prints binary data!
        print($toy->sump_meta(),"\n");
    } elsif ($cmd eq 'sumprun') {
        $toy->sump_run();
        # TODO - do something with the data..
    } elsif ($cmd eq 'version') {
        print($toy->get_version(),"\n");
    } elsif ($cmd eq 'raw') {
        $toy->write(pack('H*',$ARGV[1]));
        my $maxlen = $ARGV[2];

        my $data = '';
        while (length($data) < $maxlen) {
            my ($count,$buf) = $toy->read(128);
            $data .= $buf;
        }
    } else {
        die("unknown command");
    }

}
main();

